#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: cn.silen_dev.sarcoidosis
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/Sarcoidosis
    username: root
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver